server.port=8000

#OLLAMA
#spring.ai.ollama.base-url=localhost:11434
#Default url is localhost:11434. So no need to set.
#spring.ai.ollama.embedding.enabled=true
#It is enabled by default.
spring.ai.ollama.embedding.model=nomic-embed-text
#spring.ai.ollama.chat.model=llama3.2

#Groq properties
spring.ai.openai.base-url=https://api.groq.com/openai
spring.ai.openai.api-key=${GROQ_API_KEY}
#Groq for embedding - we are not using this
spring.ai.openai.embedding.model=nomic-embed-text-v1.5
#Groq for chat
#Although we are setting spring.ai.openai.chat.model below, we still have to set it again in EpicComicStore
spring.ai.openai.chat.model=llama-3.1-8b-instant

spring.datasource.url=jdbc:postgresql://localhost:5432/vector_store
spring.datasource.username=postgres
spring.datasource.password=postgres

#spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.index-type=NONE
#Indexing is disabled because the llama2 embedding model produces embeddings with dimension 4096 and pgvector cannot index vectors with more than 2000 dimensions.


#For allowing to upload large image fles to search
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
server.tomcat.max-swallow-size=100MB
